### ISSUE TITLE
Application Crash on Initial Load [Win 10 Pro x64]

### ISSUE THREAD

**Issue by littleneutrino** [xcjs/tray-webview#1]
Faulting application name: NotificationWebView.exe, version: 1.0.0.0, time stamp: 0x566bc87d
Faulting module name: libcef.dll, version: 3.2357.1287.0, time stamp: 0x55c655fd
Exception code: 0x80000003
Fault offset: 0x00000000001a916d
Faulting process id: 0x2460
Faulting application start time: 0x01d134e818e33d8a
Faulting application path: C:\Program Files\XCJS\NotificationWebView\NotificationWebView.exe
Faulting module path: C:\Program Files\XCJS\NotificationWebView\libcef.dll
Report Id: 8eace1c0-590b-4f1b-ace2-4a1596eb48f7
Faulting package full name: 
Faulting package-relative application ID:

**Comment by littleneutrino** [comment]
Fault bucket 120372514070, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 120325421519

Problem signature:
P1: NotificationWebView.exe
P2: 1.0.0.0
P3: 566bc87d
P4: libcef.dll
P5: 3.2357.1287.0
P6: 55c655fd
P7: 80000003
P8: 00000000001a916d
P9: 
P10: 

Analysis symbol: 
Rechecking for solution: 0
Report Id: 8eace1c0-590b-4f1b-ace2-4a1596eb48f7
Report Status: 8
Hashed bucket: 68dd3e0bdfeedf3f5bd0cefbcd6f15c6

**Comment by xcjs** [comment]
Thanks for reporting the issue!

I think this is most likely a missing runtime dependency needed by libcef.dll. I'll try a fresh Windows 10 install and see what's missing.

**Comment by xcjs** [comment]
Do you have the Microsoft Visual Studio C++ 2013 Redistributable (x64) installed? I believe that's required to run NotificationWebView.

It can be downloaded here: https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by littleneutrino** [comment]
yes i have it installed however,i will remove and reinstall it.

**Comment by littleneutrino** [comment]
re-moved, rebooted, re-installed, same error.

**Comment by xcjs** [comment]
I'll continue looking into this.

**Comment by xcjs** [comment]
Alright, I was incorrect. You'll need to install the Microsoft Visual C++ 2012 x64 Redistributable.

**Comment by xcjs** [comment]
Here's a link: https://www.microsoft.com/en-us/download/details.aspx?id=30679

**Comment by xcjs** [comment]
I'll try and get the installer to include the redistributable as well.

**Comment by littleneutrino** [comment]
Already installed. now what?

**Comment by xcjs** [comment]
Was the error message you copied in from the Event Viewer? If not, can you check the Application log from the Event Viewer after launching the application and let me know if you see anything related?

**Comment by xcjs** [comment]
I'm also double-checking my work in the virtual machine.

**Comment by xcjs** [comment]
The new installer downloads and installs the Visual C++ 2012 Redistributable which solves this issue.
